heat_template_version: 2013-05-23

description: >
  Template that just defines a single compute instance.

resources:
  my_server:
    type: OS::Nova::Server
    properties:
      key_name: dropbear-angus
      image: fedora-19-i386-heat-cfntools
      flavor: m1.tiny
